# ServiceMonitor for Prometheus Operator integration
# Provides automatic discovery and configuration of monitoring targets

---
# VPA ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vpa-recommender
  namespace: auction-infrastructure
  labels:
    app: vpa-recommender
spec:
  selector:
    matchLabels:
      app: vpa-recommender
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scheme: http
      tlsConfig:
        insecureSkipVerify: true
---
# Prometheus ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: auction-infrastructure
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  endpoints:
    - port: http-metrics
      interval: 30s
      path: /metrics
      scheme: http
---
# Kube State Metrics ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  namespace: auction-infrastructure
  labels:
    app: kube-state-metrics
spec:
  selector:
    matchLabels:
      app: kube-state-metrics
  endpoints:
    - port: http-metrics
      interval: 30s
      path: /metrics
      scheme: http
    - port: telemetry
      interval: 30s
      path: /metrics
      scheme: http
---
# Node Exporter ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  namespace: auction-infrastructure
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scheme: http
