{{- if .Values.infrastructure.nats.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats-streaming
  namespace: {{ .Values.namespace }}
spec:
  serviceName: nats-streaming
  replicas: 1
  selector:
    matchLabels:
      app: nats-streaming
  template:
    metadata:
      labels:
        app: nats-streaming
    spec:
      containers:
        - name: nats-streaming
          image: nats-streaming:latest
          args: [
            "-p",
            "4222",
            "-m",
            "8222",
            "-hbi",
            "5s",
            "-hbt",
            "5s",
            "-hbf",
            "2",
            "-SD",
            "-cid",
            "auction"
          ]
          ports:
            - containerPort: 4222
              name: client
            - containerPort: 8222
              name: monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: nats-streaming
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: monitoring
      port: 8222
      targetPort: 8222
  selector:
    app: nats-streaming
{{- end }}
