# Environment-specific patches for replica counts
# Development Environment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: auction-system
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: auction-system
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bid
  namespace: auction-system
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: listings
  namespace: auction-system
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: auction-system
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
  namespace: auction-system
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: auction-system
spec:
  replicas: 1
