version: '3.8'

services:
  # Infrastructure Services
  nats-streaming:
    image: nats-streaming:0.24.6
    container_name: auction-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: [
      "-p", "4222",
      "-m", "8222",
      "-hbi", "5s",
      "-hbt", "5s",
      "-hbf", "2",
      "-SD",
      "-cid", "auction"
    ]
    networks:
      - auction-network
    restart: unless-stopped
    healthcheck:
      disable: true

  redis:
    image: redis:7-alpine
    container_name: auction-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - auction-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # MySQL Databases
  auth-mysql:
    image: mysql:8.0
    container_name: auction-auth-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: auth
    ports:
      - "3306:3306"
    volumes:
      - auth-mysql-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - auction-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-password}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  bid-mysql:
    image: mysql:8.0
    container_name: auction-bid-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: bid
    ports:
      - "3307:3306"
    volumes:
      - bid-mysql-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - auction-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-password}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  listings-mysql:
    image: mysql:8.0
    container_name: auction-listings-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: listings
    ports:
      - "3308:3306"
    volumes:
      - listings-mysql-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - auction-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-password}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  payments-mysql:
    image: mysql:8.0
    container_name: auction-payments-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: payments
    ports:
      - "3309:3306"
    volumes:
      - payments-mysql-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - auction-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-password}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  profile-mysql:
    image: mysql:8.0
    container_name: auction-profile-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: profile
    ports:
      - "3310:3306"
    volumes:
      - profile-mysql-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - auction-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-password}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Application Services (Pull Only - No Build)
  api-gateway:
    image: pramithamj/auction-website-ms-api-gateway:${IMAGE_TAG:-latest}
    container_name: auction-api-gateway
    ports:
      - "${API_GATEWAY_PORT:-3001}:3001"
    environment:
      - PORT=3001
      - NODE_ENV=${NODE_ENV:-production}
      - AUTH_SERVICE_URL=http://auth:3101
      - BID_SERVICE_URL=http://bid:3102
      - LISTINGS_SERVICE_URL=http://listings:3103
      - PAYMENTS_SERVICE_URL=http://payments:3104
      - PROFILE_SERVICE_URL=http://profile:3105
      - EMAIL_SERVICE_URL=http://email:3106
      - SAGA_ORCHESTRATOR_URL=http://saga-orchestrator:3108
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:3000,http://localhost:3001}
      - JWT_KEY=${JWT_KEY:-qLYn6wQ9vy8HS0LwuEsNyWgG3oYc8Mk1yRLotUXgrR/uEbEN9I6mdjnLAcjWiVuR}
    depends_on:
      nats-streaming:
        condition: service_started
      auth:
        condition: service_started
      bid:
        condition: service_started
      listings:
        condition: service_started
      payments:
        condition: service_started
      profile:
        condition: service_started
      email:
        condition: service_started
      saga-orchestrator:
        condition: service_started
    networks:
      - auction-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  auth:
    image: pramithamj/auction-website-ms-auth:${IMAGE_TAG:-latest}
    container_name: auction-auth
    ports:
      - "3101:3101"
    environment:
      - PORT=3101
      - NODE_ENV=${NODE_ENV:-production}
      - JWT_KEY=${JWT_KEY:-qLYn6wQ9vy8HS0LwuEsNyWgG3oYc8Mk1yRLotUXgrR/uEbEN9I6mdjnLAcjWiVuR}
      - AUTH_MYSQL_URI=mysql://root:${MYSQL_ROOT_PASSWORD:-password}@auth-mysql:3306/auth
      - NATS_URL=nats://nats-streaming:4222
      - NATS_CLUSTER_ID=auction
      - NATS_CLIENT_ID=auth-service
      - SAGA_ORCHESTRATOR_URL=http://saga-orchestrator:3108
    depends_on:
      auth-mysql:
        condition: service_healthy
      nats-streaming:
        condition: service_started
    networks:
      - auction-network
    restart: unless-stopped

  bid:
    image: pramithamj/auction-website-ms-bid:${IMAGE_TAG:-latest}
    container_name: auction-bid
    ports:
      - "3102:3102"
    environment:
      - PORT=3102
      - NODE_ENV=${NODE_ENV:-production}
      - JWT_KEY=${JWT_KEY:-qLYn6wQ9vy8HS0LwuEsNyWgG3oYc8Mk1yRLotUXgrR/uEbEN9I6mdjnLAcjWiVuR}
      - BID_MYSQL_URI=mysql://root:${MYSQL_ROOT_PASSWORD:-password}@bid-mysql:3306/bid
      - NATS_URL=nats://nats-streaming:4222
      - NATS_CLUSTER_ID=auction
      - NATS_CLIENT_ID=bid-service
    depends_on:
      bid-mysql:
        condition: service_healthy
      nats-streaming:
        condition: service_started
      listings:
        condition: service_started
    networks:
      - auction-network
    restart: unless-stopped

  listings:
    image: pramithamj/auction-website-ms-listing:${IMAGE_TAG:-latest}
    container_name: auction-listings
    ports:
      - "3103:3103"
    environment:
      - PORT=3103
      - NODE_ENV=${NODE_ENV:-production}
      - JWT_KEY=${JWT_KEY:-qLYn6wQ9vy8HS0LwuEsNyWgG3oYc8Mk1yRLotUXgrR/uEbEN9I6mdjnLAcjWiVuR}
      - LISTINGS_MYSQL_URI=mysql://root:${MYSQL_ROOT_PASSWORD:-password}@listings-mysql:3306/listings
      - NATS_URL=nats://nats-streaming:4222
      - NATS_CLUSTER_ID=auction
      - NATS_CLIENT_ID=listings-service
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
    depends_on:
      listings-mysql:
        condition: service_healthy
      nats-streaming:
        condition: service_started
    networks:
      - auction-network
    restart: unless-stopped

  payments:
    image: pramithamj/auction-website-ms-payment:${IMAGE_TAG:-latest}
    container_name: auction-payments
    ports:
      - "3104:3104"
    environment:
      - PORT=3104
      - NODE_ENV=${NODE_ENV:-production}
      - JWT_KEY=${JWT_KEY:-qLYn6wQ9vy8HS0LwuEsNyWgG3oYc8Mk1yRLotUXgrR/uEbEN9I6mdjnLAcjWiVuR}
      - PAYMENTS_MYSQL_URI=mysql://root:${MYSQL_ROOT_PASSWORD:-password}@payments-mysql:3306/payments
      - NATS_URL=nats://nats-streaming:4222
      - NATS_CLUSTER_ID=auction
      - NATS_CLIENT_ID=payments-service
      - STRIPE_KEY=${STRIPE_KEY}
    depends_on:
      payments-mysql:
        condition: service_healthy
      nats-streaming:
        condition: service_started
    networks:
      - auction-network
    restart: unless-stopped

  profile:
    image: pramithamj/auction-website-ms-profile:${IMAGE_TAG:-latest}
    container_name: auction-profile
    ports:
      - "3105:3105"
    environment:
      - PORT=3105
      - NODE_ENV=${NODE_ENV:-production}
      - JWT_KEY=${JWT_KEY:-qLYn6wQ9vy8HS0LwuEsNyWgG3oYc8Mk1yRLotUXgrR/uEbEN9I6mdjnLAcjWiVuR}
      - PROFILE_MYSQL_URI=mysql://root:${MYSQL_ROOT_PASSWORD:-password}@profile-mysql:3306/profile
      - NATS_URL=nats://nats-streaming:4222
      - NATS_CLUSTER_ID=auction
      - NATS_CLIENT_ID=profile-service
    depends_on:
      profile-mysql:
        condition: service_healthy
      nats-streaming:
        condition: service_started
    networks:
      - auction-network
    restart: unless-stopped

  email:
    image: pramithamj/auction-website-ms-email:${IMAGE_TAG:-latest}
    container_name: auction-email
    ports:
      - "3106:3106"
    environment:
      - PORT=3106
      - NODE_ENV=${NODE_ENV:-production}
      - JWT_KEY=${JWT_KEY:-qLYn6wQ9vy8HS0LwuEsNyWgG3oYc8Mk1yRLotUXgrR/uEbEN9I6mdjnLAcjWiVuR}
      - NATS_URL=nats://nats-streaming:4222
      - NATS_CLUSTER_ID=auction
      - NATS_CLIENT_ID=email-service
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - AUTH_SERVICE_URL=http://auth:3101
      - LISTINGS_SERVICE_URL=http://listings:3103
    depends_on:
      nats-streaming:
        condition: service_started
    networks:
      - auction-network
    restart: unless-stopped

  saga-orchestrator:
    image: pramithamj/auction-website-ms-saga-orchestrator:${IMAGE_TAG:-latest}
    container_name: auction-saga-orchestrator
    ports:
      - "3108:3108"
    environment:
      - PORT=3108
      - NODE_ENV=${NODE_ENV:-production}
      - JWT_KEY=${JWT_KEY:-qLYn6wQ9vy8HS0LwuEsNyWgG3oYc8Mk1yRLotUXgrR/uEbEN9I6mdjnLAcjWiVuR}
      - NATS_URL=nats://nats-streaming:4222
      - NATS_CLUSTER_ID=auction
      - NATS_CLIENT_ID=saga-orchestrator-service
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
      nats-streaming:
        condition: service_started
    networks:
      - auction-network
    restart: unless-stopped

  expiration:
    image: pramithamj/auction-website-ms-expiration:${IMAGE_TAG:-latest}
    container_name: auction-expiration
    ports:
      - "3107:3107"
    environment:
      - PORT=3107
      - NODE_ENV=${NODE_ENV:-production}
      - JWT_KEY=${JWT_KEY:-qLYn6wQ9vy8HS0LwuEsNyWgG3oYc8Mk1yRLotUXgrR/uEbEN9I6mdjnLAcjWiVuR}
      - NATS_URL=nats://nats-streaming:4222
      - NATS_CLUSTER_ID=auction
      - NATS_CLIENT_ID=expiration-service
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
      nats-streaming:
        condition: service_started
    networks:
      - auction-network
    restart: unless-stopped

  frontend:
    image: pramithamj/auction-website-ms-frontend:${IMAGE_TAG:-latest}
    container_name: auction-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3001}
      - NEXT_PUBLIC_API_GATEWAY_PORT=${NEXT_PUBLIC_API_GATEWAY_PORT:-3001}
      - SERVER_API_URL=${SERVER_API_URL:-http://api-gateway:3001}
      - NEXT_PUBLIC_SERVER_IP=${SERVER_IP:-localhost}
      - NEXT_PUBLIC_LISTINGS_SOCKET_URL=http://${SERVER_IP:-localhost}:3103/socket
      - WATCHPACK_POLLING=true
    depends_on:
      api-gateway:
        condition: service_started
    networks:
      - auction-network
    restart: unless-stopped

volumes:
  redis-data:
    driver: local
  auth-mysql-data:
    driver: local
  bid-mysql-data:
    driver: local
  listings-mysql-data:
    driver: local
  payments-mysql-data:
    driver: local
  profile-mysql-data:
    driver: local

networks:
  auction-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
