apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auction-ingress
  namespace: auction-system
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '30'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/cors.enabled: 'true'
    alb.ingress.kubernetes.io/cors.allow-origin: '*'
    alb.ingress.kubernetes.io/cors.allow-methods: 'GET,POST,PUT,DELETE,OPTIONS'
    alb.ingress.kubernetes.io/cors.allow-headers: 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization'
spec:
  ingressClassName: alb
  rules:
    # Default rule for ALB - no host restriction
    - http:
        paths:
          # API routes
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway-service
                port:
                  number: 3001
          # Frontend routes (catch-all)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000
