apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.apiGateway.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.services.apiGateway.name }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.services.apiGateway.name }}
