apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.frontend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.services.frontend.name }}
    {{- include "auction.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.services.frontend.name }}
