apiVersion: v1
kind: ConfigMap
metadata:
  name: auction-config
  namespace: auction-system
data:
  # Environment
  NODE_ENV: "development"
  
  # NATS Configuration
  NATS_URL: "nats://nats-streaming.auction-infrastructure.svc.cluster.local:4222"
  NATS_CLUSTER_ID: "auction"
  
  # Redis Configuration
  REDIS_HOST: "redis.auction-infrastructure.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_URL: "redis://redis.auction-infrastructure.svc.cluster.local:6379"
  
  # Database Host Configuration (passwords moved to secrets)
  AUTH_MYSQL_HOST: "auth-mysql.auction-infrastructure.svc.cluster.local"
  BID_MYSQL_HOST: "bid-mysql.auction-infrastructure.svc.cluster.local"
  LISTINGS_MYSQL_HOST: "listings-mysql.auction-infrastructure.svc.cluster.local"
  PAYMENTS_MYSQL_HOST: "payments-mysql.auction-infrastructure.svc.cluster.local"
  PROFILE_MYSQL_HOST: "profile-mysql.auction-infrastructure.svc.cluster.local"
  MYSQL_PORT: "3306"
  
  # Service URLs - Using internal cluster DNS
  AUTH_SERVICE_URL: "http://auth-service.auction-system.svc.cluster.local:3101"
  BID_SERVICE_URL: "http://bid-service.auction-system.svc.cluster.local:3102"
  LISTINGS_SERVICE_URL: "http://listings-service.auction-system.svc.cluster.local:3103"
  PAYMENTS_SERVICE_URL: "http://payments-service.auction-system.svc.cluster.local:3104"
  PROFILE_SERVICE_URL: "http://profile-service.auction-system.svc.cluster.local:3105"
  EMAIL_SERVICE_URL: "http://email-service.auction-system.svc.cluster.local:3106"
  SAGA_ORCHESTRATOR_URL: "http://saga-orchestrator-service.auction-system.svc.cluster.local:3108"
  
  # AWS Configuration
  AWS_REGION: "us-east-1"
  
  # Jaeger/OpenTelemetry Configuration
  JAEGER_ENDPOINT: "http://jaeger.auction-infrastructure.svc.cluster.local:14268/api/traces"
  OTEL_RESOURCE_ATTRIBUTES: "service.version=1.0.0,deployment.environment=development"
  OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger.auction-infrastructure.svc.cluster.local:14268/api/traces"
  OTEL_TRACES_EXPORTER: "jaeger"
  OTEL_PROPAGATORS: "tracecontext,baggage"
  OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED: "true"
  
  # CORS Configuration - Updated for EC2
  CORS_ORIGIN: "http://localhost:3000,http://auction.local,http://api.auction.local,http://44.207.118.24:3000,http://44.207.118.24:3001,http://44.207.118.24"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: auction-system
data:
  NEXT_PUBLIC_API_URL: "http://adfe9b3a9967d49a29e008b64cf88af7-1746713329.us-east-2.elb.amazonaws.com"
  SERVER_API_URL: "http://adfe9b3a9967d49a29e008b64cf88af7-1746713329.us-east-2.elb.amazonaws.com"
  NEXT_PUBLIC_SERVER_IP: "adfe9b3a9967d49a29e008b64cf88af7-1746713329.us-east-2.elb.amazonaws.com"
  NEXT_PUBLIC_LISTINGS_SOCKET_URL: "ws://adfe9b3a9967d49a29e008b64cf88af7-1746713329.us-east-2.elb.amazonaws.com/socket.io"
  WATCHPACK_POLLING: "true"
  # Stripe Publishable Key for Frontend
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "pk_test_51S2nYUISCKB90A64dJuGIucQ0uNyzegEJlX8to6xKtEZ2eJ4ghlH3oEknTSG3jfL91I7NbRaMHeVLtEHwmOodi4b00ZP9dyn0G"
