# AWS Load Balancer Controller
# This should be deployed via Helm or EKS add-on, but here's the ServiceAccount for reference

apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/AmazonEKSLoadBalancerControllerRole
---
# Install command for AWS Load Balancer Controller:
# helm repo add eks https://aws.github.io/eks-charts
# helm repo update
# helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
#   -n kube-system \
#   --set clusterName=${CLUSTER_NAME} \
#   --set serviceAccount.create=false \
#   --set serviceAccount.name=aws-load-balancer-controller
