# NATS Streaming Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-streaming
  namespace: auction-infrastructure
  labels:
    app: nats-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-streaming
  template:
    metadata:
      labels:
        app: nats-streaming
    spec:
      containers:
      - name: nats-streaming
        image: nats-streaming:0.24.6
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 8222
          name: monitor
        args:
        - "-p"
        - "4222"
        - "-m"
        - "8222"
        - "-hbi"
        - "5s"
        - "-hbt"
        - "5s"
        - "-hbf"
        - "2"
        - "-SD"
        - "-cid"
        - "auction"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        volumeMounts:
        - name: nats-data
          mountPath: /data
      volumes:
      - name: nats-data
        persistentVolumeClaim:
          claimName: nats-streaming-pvc
      securityContext:
        fsGroup: 999
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nats-streaming
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: nats-streaming
  namespace: auction-infrastructure
spec:
  selector:
    app: nats-streaming
  ports:
  - name: client
    port: 4222
    targetPort: 4222
  - name: monitor
    port: 8222
    targetPort: 8222
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-streaming-pvc
  namespace: auction-infrastructure
  annotations:
    volume.beta.kubernetes.io/storage-class: auction-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: auction-storage
  resources:
    requests:
      storage: 10Gi
