# StorageClass for EKS deployment using gp3 EBS volumes
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: auction-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  encrypted: "true"
  iops: "3000"
  throughput: "125"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
---
# Alternative StorageClass for EKS using gp3 with higher performance
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: auction-standard-high-perf
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  encrypted: "true"
  iops: "16000"
  throughput: "1000"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
