# Bid Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bid
  namespace: auction-system
  labels:
    app: bid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bid
  template:
    metadata:
      labels:
        app: bid
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: bid
        image: pramithamj/auction-website-ms-bid:latest
        ports:
        - containerPort: 3102
        env:
        - name: PORT
          value: "3102"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: NODE_ENV
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: auction-secrets
              key: JWT_KEY
        - name: BID_MYSQL_URI
          valueFrom:
            secretKeyRef:
              name: auction-secrets
              key: BID_MYSQL_URI
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: NATS_URL
        - name: NATS_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: NATS_CLUSTER_ID
        - name: NATS_CLIENT_ID
          value: "bid-service"
        # OpenTelemetry/Jaeger Configuration
        - name: JAEGER_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: JAEGER_ENDPOINT
        - name: OTEL_SERVICE_NAME
          value: "bid-service"
        - name: OTEL_RESOURCE_ATTRIBUTES
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: OTEL_RESOURCE_ATTRIBUTES
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "250m"
        # startupProbe:
        #   httpGet:
        #     path: /health
        #     port: 3102
        #   failureThreshold: 60
        #   periodSeconds: 5
        #   timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3102
          initialDelaySeconds: 90
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /ready
            port: 3102
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 8
---
apiVersion: v1
kind: Service
metadata:
  name: bid-service
  namespace: auction-system
spec:
  selector:
    app: bid
  ports:
  - port: 3102
    targetPort: 3102
    name: http
  type: ClusterIP
