# Email Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  namespace: auction-system
  labels:
    app: email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: email
        image: pramithamj/auction-website-ms-email:latest
        ports:
        - containerPort: 3106
        env:
        - name: PORT
          value: "3106"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: NODE_ENV
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: auction-secrets
              key: JWT_KEY
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: NATS_URL
        - name: NATS_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: NATS_CLUSTER_ID
        - name: NATS_CLIENT_ID
          value: "email-service"
        - name: EMAIL
          valueFrom:
            secretKeyRef:
              name: auction-secrets
              key: EMAIL
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auction-secrets
              key: EMAIL_PASSWORD
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: AUTH_SERVICE_URL
        - name: LISTINGS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: LISTINGS_SERVICE_URL
        # OpenTelemetry/Jaeger Configuration
        - name: JAEGER_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: JAEGER_ENDPOINT
        - name: OTEL_SERVICE_NAME
          value: "email-service"
        - name: OTEL_RESOURCE_ATTRIBUTES
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: OTEL_RESOURCE_ATTRIBUTES
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "100m"
        # startupProbe:
        #   httpGet:
        #     path: /health
        #     port: 3106
        #   failureThreshold: 30
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 3106
        #   initialDelaySeconds: 60
        #   periodSeconds: 15
        #   timeoutSeconds: 5
        #   failureThreshold: 5
        # readinessProbe:
        #   httpGet:
        #     path: /ready
        #     port: 3106
        #   initialDelaySeconds: 45
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        #   failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: auction-system
spec:
  selector:
    app: email
  ports:
  - port: 3106
    targetPort: 3106
    name: http
  type: ClusterIP
