# Listings Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: listings
  namespace: auction-system
  labels:
    app: listings
spec:
  replicas: 2
  selector:
    matchLabels:
      app: listings
  template:
    metadata:
      labels:
        app: listings
    spec:
      containers:
      - name: listings
        image: pramithamj/auction-website-ms-listing:latest
        ports:
        - containerPort: 3103
        env:
        - name: PORT
          value: "3103"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: NODE_ENV
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: auction-secrets
              key: JWT_KEY
        - name: LISTINGS_MYSQL_URI
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: LISTINGS_MYSQL_URI
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: NATS_URL
        - name: NATS_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: NATS_CLUSTER_ID
        - name: NATS_CLIENT_ID
          value: "listings-service"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: auction-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: auction-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: AWS_REGION
        - name: AWS_S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: auction-secrets
              key: AWS_S3_BUCKET_NAME
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        # Disable health checks temporarily
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 3103
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        #   failureThreshold: 3
        # readinessProbe:
        #   httpGet:
        #     path: /ready
        #     port: 3103
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        #   failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: listings-service
  namespace: auction-system
spec:
  selector:
    app: listings
  ports:
  - port: 3103
    targetPort: 3103
    name: http
  type: ClusterIP
