# Payments Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: auction-system
  labels:
    app: payments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: payments
        image: pramithamj/auction-website-ms-payment:latest
        ports:
        - containerPort: 3104
        env:
        - name: PORT
          value: "3104"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: NODE_ENV
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: auction-secrets
              key: JWT_KEY
        - name: PAYMENTS_MYSQL_URI
          valueFrom:
            secretKeyRef:
              name: auction-secrets
              key: PAYMENTS_MYSQL_URI
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: NATS_URL
        - name: NATS_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: NATS_CLUSTER_ID
        - name: NATS_CLIENT_ID
          value: "payments-service"
        - name: STRIPE_KEY
          valueFrom:
            secretKeyRef:
              name: auction-secrets
              key: STRIPE_KEY
        # OpenTelemetry/Jaeger Configuration
        - name: JAEGER_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: JAEGER_ENDPOINT
        - name: OTEL_SERVICE_NAME
          value: "payments-service"
        - name: OTEL_RESOURCE_ATTRIBUTES
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: OTEL_RESOURCE_ATTRIBUTES
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "250m"
        # startupProbe:
        #   httpGet:
        #     path: /health
        #     port: 3104
        #   failureThreshold: 60
        #   periodSeconds: 5
        #   timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3104
          initialDelaySeconds: 90
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /ready
            port: 3104
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 8
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: auction-system
spec:
  selector:
    app: payments
  ports:
  - port: 3104
    targetPort: 3104
    name: http
  type: ClusterIP
