# Payments Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: auction-system
  labels:
    app: payments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: pramithamj/auction-website-ms-payment:latest
        ports:
        - containerPort: 3104
        env:
        - name: PORT
          value: "3104"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: NODE_ENV
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: auction-secrets
              key: JWT_KEY
        - name: PAYMENTS_MYSQL_URI
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: PAYMENTS_MYSQL_URI
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: NATS_URL
        - name: NATS_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: NATS_CLUSTER_ID
        - name: NATS_CLIENT_ID
          value: "payments-service"
        - name: STRIPE_KEY
          valueFrom:
            secretKeyRef:
              name: auction-secrets
              key: STRIPE_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3104
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3104
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: auction-system
spec:
  selector:
    app: payments
  ports:
  - port: 3104
    targetPort: 3104
    name: http
  type: ClusterIP
