# Profile Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
  namespace: auction-system
  labels:
    app: profile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: profile
        image: pramithamj/auction-website-ms-profile:latest
        ports:
        - containerPort: 3105
        env:
        - name: PORT
          value: "3105"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: NODE_ENV
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: auction-secrets
              key: JWT_KEY
        - name: PROFILE_MYSQL_URI
          valueFrom:
            secretKeyRef:
              name: auction-secrets
              key: PROFILE_MYSQL_URI
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: NATS_URL
        - name: NATS_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: NATS_CLUSTER_ID
        - name: NATS_CLIENT_ID
          value: "profile-service"
        # OpenTelemetry/Jaeger Configuration
        - name: JAEGER_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: JAEGER_ENDPOINT
        - name: OTEL_SERVICE_NAME
          value: "profile-service"
        - name: OTEL_RESOURCE_ATTRIBUTES
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: OTEL_RESOURCE_ATTRIBUTES
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "250m"
        startupProbe:
          httpGet:
            path: /health
            port: 3105
          failureThreshold: 60
          periodSeconds: 5
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3105
          initialDelaySeconds: 90
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /ready
            port: 3105
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 8
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: auction-system
spec:
  selector:
    app: profile
  ports:
  - port: 3105
    targetPort: 3105
    name: http
  type: ClusterIP
