# Profile Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
  namespace: auction-system
  labels:
    app: profile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - name: profile
        image: pramithamj/auction-website-ms-profile:latest
        ports:
        - containerPort: 3105
        env:
        - name: PORT
          value: "3105"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: NODE_ENV
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: auction-secrets
              key: JWT_KEY
        - name: PROFILE_MYSQL_URI
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: PROFILE_MYSQL_URI
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: NATS_URL
        - name: NATS_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              name: auction-config
              key: NATS_CLUSTER_ID
        - name: NATS_CLIENT_ID
          value: "profile-service"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3105
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3105
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: auction-system
spec:
  selector:
    app: profile
  ports:
  - port: 3105
    targetPort: 3105
    name: http
  type: ClusterIP
