# fluent-bit-values.yaml
config:
  inputs: |
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Tag               kube.*
        Parser            docker
        Mem_Buf_Limit     5MB
        Refresh_Interval  5
    [INPUT]
        Name              systemd
        Tag               host.*
        Systemd_Filter    _SYSTEMD_UNIT=kubelet.service
        Systemd_Filter    _SYSTEMD_UNIT=docker.service
        Strip_Underscores On
  service: |
    [SERVICE]
        Log_Level         info
        Parsers_File      /fluent-bit/etc/parsers.conf
        HTTP_Server       On
        HTTP_Listen       0.0.0.0
        HTTP_Port         2020

  outputs: |
    [OUTPUT]
        Name              opensearch
        Match             *
        Host              192.168.49.1
        Port              9200
        Index             minikube-logs
        Logstash_Format   On
        Replace_Dots      On
        TLS               On
        TLS.Verify        Off
        HTTP_User         admin
        HTTP_Passwd       abcABC@123
        Retry_Limit       3
        Suppress_Type_Name On
        Trace_Error       On
        Trace_Output      On
        
    [FILTER]
        Name modify
        Match *
        Rename kubernetes.labels.app kubernetes_labels_app

