apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-mysql-pvc
  namespace: auction
  labels:
    app: auction-microservices
    component: auth-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard # Update based on your cluster's storage class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bid-mysql-pvc
  namespace: auction
  labels:
    app: auction-microservices
    component: bid-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: listings-mysql-pvc
  namespace: auction
  labels:
    app: auction-microservices
    component: listings-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payments-mysql-pvc
  namespace: auction
  labels:
    app: auction-microservices
    component: payments-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profile-mysql-pvc
  namespace: auction
  labels:
    app: auction-microservices
    component: profile-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: auction
  labels:
    app: auction-microservices
    component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
---
