apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: auction-system
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - port: 3001
      targetPort: 3001
      name: http
  type: ClusterIP
