apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: auction-system
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  type: ClusterIP
