apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auction-system
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3101
      targetPort: 3101
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: bid-service
  namespace: auction-system
spec:
  selector:
    app: bid
  ports:
    - name: bid
      protocol: TCP
      port: 3102
      targetPort: 3102
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: listings-service
  namespace: auction-system
spec:
  selector:
    app: listings
  ports:
    - name: listings
      protocol: TCP
      port: 3103
      targetPort: 3103
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: auction-system
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3104
      targetPort: 3104
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: auction-system
spec:
  selector:
    app: profile
  ports:
    - name: profile
      protocol: TCP
      port: 3105
      targetPort: 3105
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: auction-system
  labels:
    app: email
spec:
  selector:
    app: email
  ports:
    - port: 3106
      targetPort: 3106
      name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: expiration-service
  namespace: auction-system
  labels:
    app: expiration
spec:
  selector:
    app: expiration
  ports:
    - port: 3107
      targetPort: 3107
      name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: saga-orchestrator-service
  namespace: auction-system
  labels:
    app: saga-orchestrator
spec:
  selector:
    app: saga-orchestrator
  ports:
    - port: 3108
      targetPort: 3108
      name: http
  type: ClusterIP
