apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auction-system
  labels:
    app: auth
spec:
  selector:
    app: auth
  ports:
  - port: 3101
    targetPort: 3101
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: bid-service
  namespace: auction-system
  labels:
    app: bid
spec:
  selector:
    app: bid
  ports:
  - port: 3102
    targetPort: 3102
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: listings-service
  namespace: auction-system
  labels:
    app: listings
spec:
  selector:
    app: listings
  ports:
  - port: 3103
    targetPort: 3103
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: auction-system
  labels:
    app: payments
spec:
  selector:
    app: payments
  ports:
  - port: 3104
    targetPort: 3104
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: auction-system
  labels:
    app: profile
spec:
  selector:
    app: profile
  ports:
  - port: 3105
    targetPort: 3105
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: auction-system
  labels:
    app: email
spec:
  selector:
    app: email
  ports:
  - port: 3106
    targetPort: 3106
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: expiration-service
  namespace: auction-system
  labels:
    app: expiration
spec:
  selector:
    app: expiration
  ports:
  - port: 3107
    targetPort: 3107
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: saga-orchestrator-service
  namespace: auction-system
  labels:
    app: saga-orchestrator
spec:
  selector:
    app: saga-orchestrator
  ports:
  - port: 3108
    targetPort: 3108
    name: http
  type: ClusterIP
