name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: pramithamj

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate version tags
      id: meta
      run: |
        # Get short commit SHA
        SHORT_SHA=$(git rev-parse --short HEAD)
        
        # Get current date
        DATE=$(date +%Y%m%d)
        
        # Generate version tag
        VERSION="v1.0.${GITHUB_RUN_NUMBER}"
        
        echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_OUTPUT
        echo "DATE=${DATE}" >> $GITHUB_OUTPUT
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
        echo "FULL_TAG=${VERSION}-${SHORT_SHA}" >> $GITHUB_OUTPUT

    - name: Build and push Common package
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./common/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-common:latest
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-common:${{ steps.meta.outputs.VERSION }}
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-common:${{ steps.meta.outputs.FULL_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Auth service
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./services/auth/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-auth:latest
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-auth:${{ steps.meta.outputs.VERSION }}
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-auth:${{ steps.meta.outputs.FULL_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Bid service
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./services/bid/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-bid:latest
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-bid:${{ steps.meta.outputs.VERSION }}
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-bid:${{ steps.meta.outputs.FULL_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Listings service
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./services/listings/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-listing:latest
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-listing:${{ steps.meta.outputs.VERSION }}
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-listing:${{ steps.meta.outputs.FULL_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Payments service
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./services/payments/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-payment:latest
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-payment:${{ steps.meta.outputs.VERSION }}
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-payment:${{ steps.meta.outputs.FULL_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Profile service
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./services/profile/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-profile:latest
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-profile:${{ steps.meta.outputs.VERSION }}
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-profile:${{ steps.meta.outputs.FULL_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Email service
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./services/email/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-email:latest
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-email:${{ steps.meta.outputs.VERSION }}
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-email:${{ steps.meta.outputs.FULL_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Expiration service
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./services/expiration/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-expiration:latest
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-expiration:${{ steps.meta.outputs.VERSION }}
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-expiration:${{ steps.meta.outputs.FULL_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Saga Orchestrator
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./services/saga-orchestrator/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-saga-orchestrator:latest
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-saga-orchestrator:${{ steps.meta.outputs.VERSION }}
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-saga-orchestrator:${{ steps.meta.outputs.FULL_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push API Gateway
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./services/api-gateway/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-api-gateway:latest
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-api-gateway:${{ steps.meta.outputs.VERSION }}
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-api-gateway:${{ steps.meta.outputs.FULL_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Frontend
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./services/frontend/Dockerfile.dev
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-frontend:latest
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-frontend:${{ steps.meta.outputs.VERSION }}
          ${{ env.DOCKER_USERNAME }}/auction-website-ms-frontend:${{ steps.meta.outputs.FULL_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Create Git Tag and Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.meta.outputs.VERSION }}
        name: Release ${{ steps.meta.outputs.VERSION }}
        body: |
          Automated release for ${{ steps.meta.outputs.VERSION }}
          DockerHub links:
          - common: https://hub.docker.com/r/${{ env.DOCKER_USERNAME }}/auction-website-ms-common
          - auth: https://hub.docker.com/r/${{ env.DOCKER_USERNAME }}/auction-website-ms-auth
          - bid: https://hub.docker.com/r/${{ env.DOCKER_USERNAME }}/auction-website-ms-bid
          - listings: https://hub.docker.com/r/${{ env.DOCKER_USERNAME }}/auction-website-ms-listing
          - payments: https://hub.docker.com/r/${{ env.DOCKER_USERNAME }}/auction-website-ms-payment
          - profile: https://hub.docker.com/r/${{ env.DOCKER_USERNAME }}/auction-website-ms-profile
          - email: https://hub.docker.com/r/${{ env.DOCKER_USERNAME }}/auction-website-ms-email
          - expiration: https://hub.docker.com/r/${{ env.DOCKER_USERNAME }}/auction-website-ms-expiration
          - saga-orchestrator: https://hub.docker.com/r/${{ env.DOCKER_USERNAME }}/auction-website-ms-saga-orchestrator
          - api-gateway: https://hub.docker.com/r/${{ env.DOCKER_USERNAME }}/auction-website-ms-api-gateway
          - frontend: https://hub.docker.com/r/${{ env.DOCKER_USERNAME }}/auction-website-ms-frontend
          Docker Images Published:
          Get the Docker images using the following tags:
          - Version: ${{ steps.meta.outputs.VERSION }}
          - Full Tag: ${{ steps.meta.outputs.FULL_TAG }}
          Commit: ${{ steps.meta.outputs.SHORT_SHA }}
          Date: ${{ steps.meta.outputs.DATE }}
      env:
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}

    - name: Summary
      run: |
        echo " Build and Push Completed!"
        echo " Version: ${{ steps.meta.outputs.VERSION }}"
        echo " Full Tag: ${{ steps.meta.outputs.FULL_TAG }}"
        echo " Date: ${{ steps.meta.outputs.DATE }}"
        echo " Commit: ${{ steps.meta.outputs.SHORT_SHA }}"
        echo ""
        echo " Docker Images pushed:"
        echo "  - common: ${{ env.DOCKER_USERNAME }}/auction-website-ms-common:${{ steps.meta.outputs.VERSION }}"
        echo "  - auth: ${{ env.DOCKER_USERNAME }}/auction-website-ms-auth:${{ steps.meta.outputs.VERSION }}"
        echo "  - bid: ${{ env.DOCKER_USERNAME }}/auction-website-ms-bid:${{ steps.meta.outputs.VERSION }}"
        echo "  - listings: ${{ env.DOCKER_USERNAME }}/auction-website-ms-listing:${{ steps.meta.outputs.VERSION }}"
        echo "  - payments: ${{ env.DOCKER_USERNAME }}/auction-website-ms-payment:${{ steps.meta.outputs.VERSION }}"
        echo "  - profile: ${{ env.DOCKER_USERNAME }}/auction-website-ms-profile:${{ steps.meta.outputs.VERSION }}"
        echo "  - email: ${{ env.DOCKER_USERNAME }}/auction-website-ms-email:${{ steps.meta.outputs.VERSION }}"
        echo "  - expiration: ${{ env.DOCKER_USERNAME }}/auction-website-ms-expiration:${{ steps.meta.outputs.VERSION }}"
        echo "  - saga-orchestrator: ${{ env.DOCKER_USERNAME }}/auction-website-ms-saga-orchestrator:${{ steps.meta.outputs.VERSION }}"
        echo "  - api-gateway: ${{ env.DOCKER_USERNAME }}/auction-website-ms-api-gateway:${{ steps.meta.outputs.VERSION }}"
        echo "  - frontend: ${{ env.DOCKER_USERNAME }}/auction-website-ms-frontend:${{ steps.meta.outputs.VERSION }}"
    
    - name: Update ArgoCD manifests
      env:
        ARGOCD_REPO: https://github.com/PramithaMJ/argocd-auctionhub.git
        ARGOCD_BRANCH: main
        FULL_TAG: ${{ steps.meta.outputs.FULL_TAG }}
        DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
      run: |
        # Clone the ArgoCD repo
        git clone --branch $ARGOCD_BRANCH $ARGOCD_REPO argocd
        cd argocd/k8s

        # Update deployment files with new image tags
        sed -i "s#image: .*/auction-website-ms-auth:.*#image: $DOCKER_USERNAME/auction-website-ms-auth:${FULL_TAG}#" ./deployments/auth.yaml
        sed -i "s#image: .*/auction-website-ms-bid:.*#image: $DOCKER_USERNAME/auction-website-ms-bid:${FULL_TAG}#" ./deployments/bid.yaml
        sed -i "s#image: .*/auction-website-ms-listing:.*#image: $DOCKER_USERNAME/auction-website-ms-listing:${FULL_TAG}#" ./deployments/listings.yaml
        sed -i "s#image: .*/auction-website-ms-payment:.*#image: $DOCKER_USERNAME/auction-website-ms-payment:${FULL_TAG}#" ./deployments/payments.yaml
        sed -i "s#image: .*/auction-website-ms-profile:.*#image: $DOCKER_USERNAME/auction-website-ms-profile:${FULL_TAG}#" ./deployments/profile.yaml
        sed -i "s#image: .*/auction-website-ms-email:.*#image: $DOCKER_USERNAME/auction-website-ms-email:${FULL_TAG}#" ./deployments/email.yaml
        sed -i "s#image: .*/auction-website-ms-expiration:.*#image: $DOCKER_USERNAME/auction-website-ms-expiration:${FULL_TAG}#" ./deployments/expiration.yaml
        sed -i "s#image: .*/auction-website-ms-saga-orchestrator:.*#image: $DOCKER_USERNAME/auction-website-ms-saga-orchestrator:${FULL_TAG}#" ./deployments/saga-orchestrator.yaml
        sed -i "s#image: .*/auction-website-ms-api-gateway:.*#image: $DOCKER_USERNAME/auction-website-ms-api-gateway:${FULL_TAG}#" ./deployments/api-gateway.yaml
        sed -i "s#image: .*/auction-website-ms-frontend:.*#image: $DOCKER_USERNAME/auction-website-ms-frontend:${FULL_TAG}#" ./deployments/frontend.yaml

        # Configure Git
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

        # Commit and push changes
        git add .
        git commit -m "Update image tags to ${FULL_TAG} [ci skip]" || echo "No changes to commit"
        git push https://$GITHUB_ACTOR:${GITHUB_TOKEN}@github.com/PramithaMJ/argocd-auctionhub.git $ARGOCD_BRANCH
